FROM php:7.4-apache
RUN docker-php-ext-install mysqli

RUN rm /var/www/html/index.html
COPY index.php /var/www/html/index.php

COPY ./ports.conf /etc/apache2/ports.conf
COPY ./apache.conf /etc/apache2/site-enabled/000-default.conf